"""Meeting Prep Skill - generates pre-meeting briefs from account data and calendar context."""

import json
import time
from pathlib import Path
from typing import Dict, Any, List, Optional
from jarvis.utils.logger import JARVISLogger
from jarvis.utils.event_bus import EventBus, Event


class MeetingPrepSkill:
    """Generates pre-meeting preparation briefs using account intelligence."""

    def __init__(self, config_manager, event_bus: EventBus):
        self.config = config_manager
        self.event_bus = event_bus
        self.logger = JARVISLogger("skill.meeting_prep")
        self._llm_manager = None

    async def start(self):
        self.event_bus.subscribe("meeting.scheduled", self._on_meeting_scheduled)
        self.logger.info("MeetingPrepSkill started")

    async def stop(self):
        self.logger.info("MeetingPrepSkill stopped")

    def set_llm_manager(self, llm_manager):
        self._llm_manager = llm_manager

    async def _on_meeting_scheduled(self, event: Event):
        account = event.data.get("account", "")
        title = event.data.get("title", "Meeting")
        attendees = event.data.get("attendees", [])
        if account:
            await self.generate_prep_brief(account, title, attendees)

    async def generate_prep_brief(self, account: str, title: str,
                                   attendees: List[str] = None) -> Dict:
        workspace = Path(str(getattr(self.config.config, 'workspace_root', '.')))
        account_dir = workspace / "ACCOUNTS" / account

        # Gather all account intelligence
        context = self._gather_account_context(account_dir)

        prompt = self._build_prep_prompt(account, title, attendees or [], context)

        brief_text = ""
        if self._llm_manager:
            from jarvis.llm.llm_client import Message
            messages = [
                Message(role="system", content=f"You are JARVIS, an AI sales assistant for {self.config.config.get('identity', {}).get('company', 'Your Company')}. Generate concise, actionable meeting prep briefs."),
                Message(role="user", content=prompt)
            ]
            brief_text = await self._llm_manager.generate_with_routing(
                messages, task_type="text", source="background"
            )

        # Write brief
        prep_dir = account_dir / "prep"
        prep_dir.mkdir(parents=True, exist_ok=True)
        date_str = time.strftime("%Y-%m-%d")
        safe_title = title.replace(" ", "_").replace("/", "-")[:50]
        brief_file = prep_dir / f"{date_str}_{safe_title}_prep.md"

        brief_content = f"""# Pre-Meeting Brief: {title}
**Account:** {account}
**Date:** {date_str}
**Attendees:** {', '.join(attendees or ['TBD'])}
**Generated by JARVIS (NVIDIA LLM)**

---

{brief_text}
"""
        brief_file.write_text(brief_content)
        self.logger.info("Meeting prep brief written", file=str(brief_file))

        return {"account": account, "brief_file": str(brief_file), "brief_text": brief_text}

    def _gather_account_context(self, account_dir: Path) -> Dict:
        context = {"discovery": "", "meddpicc": "", "meetings": "", "competitors": "", "risks": ""}

        for subdir, key in [("discovery", "discovery"), ("meddpicc", "meddpicc"),
                            ("meetings", "meetings"), ("risks", "risks")]:
            dir_path = account_dir / subdir
            if dir_path.exists():
                files = sorted(dir_path.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
                for f in files[:3]:
                    try:
                        context[key] += f"\n--- {f.name} ---\n{f.read_text()[:2000]}\n"
                    except Exception:
                        pass

        # Check for competitor mentions
        workspace = account_dir.parent.parent
        comp_dir = workspace / "MEMORY" / "competitors"
        if comp_dir.exists():
            for f in comp_dir.glob("*.json"):
                try:
                    data = json.loads(f.read_text())
                    name = data.get("name", f.stem)
                    context["competitors"] += f"\n- {name}: {json.dumps(data.get('differentiators', []))}"
                except Exception:
                    pass

        return context

    def _build_prep_prompt(self, account: str, title: str,
                            attendees: List[str], context: Dict) -> str:
        ctx_text = ""
        for key, val in context.items():
            if val.strip():
                ctx_text += f"\n### {key.title()}\n{val[:2000]}\n"

        return f"""Generate a pre-meeting preparation brief for this upcoming call.

Account: {account}
Meeting: {title}
Attendees: {', '.join(attendees) if attendees else 'Unknown'}

EXISTING ACCOUNT INTELLIGENCE:
{ctx_text if ctx_text else 'No prior intelligence available - this may be a first meeting.'}

Generate a brief with these sections:
1. **Account Overview** (what we know about this account)
2. **Meeting Objectives** (what we should aim to accomplish)
3. **Key Discovery Questions** (5-7 questions to ask, based on gaps in our knowledge)
4. **MEDDPICC Gaps** (which MEDDPICC elements are missing or weak)
5. **Competitive Landscape** (known competitors in this deal)
6. **Technical Talking Points** (yellow.ai capabilities relevant to this account)
7. **Risk Factors** (things that could derail this deal)
8. **Preparation Checklist** (what to have ready before the call)

If this is a first meeting, focus heavily on discovery questions and ICP qualification.
Be specific to the company's enterprise platform capabilities."""
