"""Meeting Summary Skill - generates structured meeting summaries from transcripts and video analysis."""

import json
import time
from pathlib import Path
from typing import Dict, Any, List, Optional
from jarvis.utils.logger import JARVISLogger
from jarvis.utils.event_bus import EventBus, Event


class MeetingSummarySkill:
    """Processes meeting transcripts and video analysis into structured summaries."""

    def __init__(self, config_manager, event_bus: EventBus):
        self.config = config_manager
        self.event_bus = event_bus
        self.logger = JARVISLogger("skill.meeting_summary")
        self._llm_manager = None

    async def start(self):
        self.event_bus.subscribe("meeting.ended", self._on_meeting_ended)
        self.logger.info("MeetingSummarySkill started")

    async def stop(self):
        self.logger.info("MeetingSummarySkill stopped")

    def set_llm_manager(self, llm_manager):
        self._llm_manager = llm_manager

    async def _on_meeting_ended(self, event: Event):
        account = event.data.get("account_name", event.data.get("account", ""))
        title = event.data.get("meeting_title", event.data.get("title", "Meeting"))
        transcript_path = event.data.get("transcript_path", "")
        slides_path = event.data.get("slides_path", "")

        if not transcript_path:
            return

        try:
            summary = await self.generate_summary(
                account=account,
                title=title,
                transcript_path=transcript_path,
                slides_path=slides_path
            )
            self.event_bus.publish(Event(
                type="meeting.summary.ready",
                source="meeting_summary_skill",
                data={"account": account, "title": title, "summary": summary}
            ))
        except Exception as e:
            self.logger.error("Failed to generate meeting summary", error=str(e))

    async def generate_summary(self, account: str, title: str,
                                transcript_path: str, slides_path: str = "") -> Dict:
        transcript = ""
        if transcript_path and Path(transcript_path).exists():
            transcript = Path(transcript_path).read_text()

        slides_analysis = []
        if slides_path and Path(slides_path).exists():
            try:
                slides_analysis = json.loads(Path(slides_path).read_text())
            except Exception:
                pass

        prompt = self._build_summary_prompt(transcript, slides_analysis, account, title)

        summary_text = ""
        if self._llm_manager:
            from jarvis.llm.llm_client import Message
            messages = [
                Message(role="system", content="You are JARVIS, an AI sales assistant. Generate structured meeting summaries."),
                Message(role="user", content=prompt)
            ]
            summary_text = await self._llm_manager.generate_with_routing(
                messages, task_type="text", source="background"
            )

        # Write summary to account folder
        workspace = Path(str(getattr(self.config.config, 'workspace_root', '.')))
        meetings_dir = workspace / "ACCOUNTS" / account / "meetings"
        meetings_dir.mkdir(parents=True, exist_ok=True)

        date_str = time.strftime("%Y-%m-%d")
        safe_title = title.replace(" ", "_").replace("/", "-")[:50]
        summary_file = meetings_dir / f"{date_str}_{safe_title}_summary.md"

        summary_content = f"""# Meeting Summary: {title}
**Account:** {account}
**Date:** {date_str}
**Generated by JARVIS (NVIDIA LLM)**

---

{summary_text}

---
*Raw transcript: {transcript_path}*
"""
        summary_file.write_text(summary_content)
        self.logger.info("Meeting summary written", file=str(summary_file))

        return {
            "account": account,
            "title": title,
            "date": date_str,
            "summary_file": str(summary_file),
            "summary_text": summary_text
        }

    def _build_summary_prompt(self, transcript: str, slides: List[Dict],
                               account: str, title: str) -> str:
        slides_text = ""
        if slides:
            slides_text = "\n\nSlide/Screen Analysis:\n"
            for i, s in enumerate(slides[:10]):
                content = s.get("slide_content", s.get("analysis", ""))
                slides_text += f"- Frame {i+1}: {content}\n"

        return f"""Analyze this meeting transcript and generate a structured summary.

Meeting: {title}
Account: {account}

TRANSCRIPT:
{transcript[:8000]}

{slides_text}

Generate a structured summary with these sections:
1. **Attendees** (extract from transcript if possible)
2. **Key Topics Discussed** (bullet points)
3. **Decisions Made** (bullet points)
4. **Action Items** (who, what, by when)
5. **MEDDPICC Signals** (any pain points, metrics, decision criteria, economic buyer signals)
6. **Competitive Mentions** (any competitor names or comparisons)
7. **Sentiment & Engagement** (overall tone, engagement level)
8. **Recommended Next Steps** (what should happen next in the sales process)
9. **Follow-up Email Draft** (short professional follow-up email based on the meeting)

Be specific and actionable. Extract real data from the transcript."""
