"""Proposal Generator Skill - assembles proposals from multiple JARVIS skill outputs."""

import json
import time
from pathlib import Path
from typing import Dict, Any, List
from jarvis.utils.logger import JARVISLogger
from jarvis.utils.event_bus import EventBus, Event


class ProposalGeneratorSkill:
    """Assembles comprehensive proposals from discovery, MEDDPICC, competitive intel, and value architecture."""

    def __init__(self, config_manager, event_bus: EventBus):
        self.config = config_manager
        self.event_bus = event_bus
        self.logger = JARVISLogger("skill.proposal_generator")
        self._llm_manager = None

    async def start(self):
        self.event_bus.subscribe("playbook.generate_proposal", self._on_generate_proposal)
        self.logger.info("ProposalGeneratorSkill started")

    async def stop(self):
        self.logger.info("ProposalGeneratorSkill stopped")

    def set_llm_manager(self, llm_manager):
        self._llm_manager = llm_manager

    async def _on_generate_proposal(self, event: Event):
        account = event.data.get("account", "")
        if account:
            await self.generate_proposal(account)

    async def generate_proposal(self, account: str) -> Dict:
        workspace = Path(str(getattr(self.config.config, 'workspace_root', '.')))
        account_dir = workspace / "ACCOUNTS" / account

        # Gather all intelligence from other skills
        intel = self._gather_intelligence(account_dir)

        prompt = self._build_proposal_prompt(account, intel)

        proposal_text = ""
        if self._llm_manager:
            from jarvis.llm.llm_client import Message
            messages = [
                Message(role="system", content=f"You are JARVIS, generating a comprehensive sales proposal for {self.config.config.get('identity', {}).get('company', 'Your Company')} enterprise platform."),
                Message(role="user", content=prompt)
            ]
            proposal_text = await self._llm_manager.generate_with_routing(
                messages, task_type="text", source="background"
            )

        # Write proposal
        proposals_dir = account_dir / "proposals"
        proposals_dir.mkdir(parents=True, exist_ok=True)
        date_str = time.strftime("%Y-%m-%d")
        proposal_file = proposals_dir / f"{date_str}_proposal.md"

        company_name = self.config.config.get("identity", {}).get("company", "Your Company")
        content = f"""# {company_name} Proposal for {account}
**Date:** {date_str}
**Generated by JARVIS (NVIDIA LLM) -- Review and polish with Claude Desktop**

---

{proposal_text}

---
*This proposal was auto-generated from account intelligence. Use Claude Desktop to create polished PPT/DOCX versions.*
"""
        proposal_file.write_text(content)
        self.logger.info("Proposal generated", account=account, file=str(proposal_file))

        self.event_bus.publish(Event(
            type="skill.triggered",
            source="proposal_generator",
            data={"skill": "proposal_generator", "account": account, "output_file": str(proposal_file)}
        ))

        return {"account": account, "proposal_file": str(proposal_file)}

    def _gather_intelligence(self, account_dir: Path) -> Dict:
        intel = {}
        for subdir in ["discovery", "meddpicc", "battlecards", "meetings", "risks", "value_architecture"]:
            dir_path = account_dir / subdir
            if dir_path.exists():
                content = ""
                for f in sorted(dir_path.glob("*.md"), key=lambda x: x.stat().st_mtime, reverse=True)[:3]:
                    try:
                        content += f"\n--- {f.name} ---\n{f.read_text()[:3000]}\n"
                    except Exception:
                        pass
                if content:
                    intel[subdir] = content
        return intel

    def _build_proposal_prompt(self, account: str, intel: Dict) -> str:
        intel_text = ""
        for key, val in intel.items():
            intel_text += f"\n### {key.replace('_', ' ').title()}\n{val}\n"

        return f"""Generate a comprehensive sales proposal for {account} based on the following intelligence gathered from discovery calls, MEDDPICC analysis, and competitive research.

ACCOUNT INTELLIGENCE:
{intel_text if intel_text else 'Limited intelligence available. Generate a template proposal.'}

Generate a proposal with these sections:

1. **Executive Summary** (1 paragraph: their problem, our solution, the financial case)
2. **Understanding Your Challenges** (based on discovery notes)
3. **Proposed Solution** (platform capabilities mapped to their pain points)
   - Use cases in scope
   - Channels (WhatsApp, Web, IVR, Email, etc.)
   - Integrations required
4. **Technical Architecture** (high-level description of how the platform fits their stack)
5. **Implementation Plan**
   - Phase 1 (6-8 weeks): Primary use cases
   - Phase 2 (4-6 weeks): Secondary use cases
   - Phase 3 (ongoing): Optimization
6. **ROI Model** (based on their numbers if available, otherwise industry benchmarks)
   - Current cost-per-contact vs. projected
   - Bot containment rate target: 60-80%
   - CSAT improvement projection
   - Payback period estimate
7. **Why Us** (competitive differentiation)
   - DynamicNLP accuracy
   - Voice-native capability
   - Unified inbox
   - Enterprise security (SOC 2, ISO 27001)
8. **Customer Proof Points** (relevant case studies)
9. **Commercial Framework** (pricing structure overview, not specific numbers)
10. **Next Steps** (recommended actions to move forward)

Write in a professional, consultative tone. Be specific where data is available, use industry benchmarks where it's not."""
