#!/usr/bin/env python3
"""
Generate jarvis.yaml with correct local paths.
Called by setup.sh with --jarvis-home argument.
"""

import argparse
import os
import sys
from pathlib import Path


def generate_config(jarvis_home: str):
    """Generate jarvis.yaml with resolved paths."""
    repo_root = Path(__file__).resolve().parent.parent
    config_path = repo_root / "jarvis" / "config" / "jarvis.yaml"

    # Resolve home directory
    jarvis_home = os.path.expanduser(jarvis_home)

    config_content = f"""# JARVIS v2 Configuration - Auto-generated by setup.sh
# Edit manually if needed, but re-run setup.sh to regenerate

# Paths (resolved for this machine)
workspace_root: "{jarvis_home}"
data_dir: "{jarvis_home}/data"
logs_dir: "{jarvis_home}/logs"
temp_dir: "{jarvis_home}/data/cache"

# Identity
identity:
  name: "Younus Shaik"
  initials: "YS"
  title: "Account Executive + Solution Consultant"
  role: "Sales & Presales"
  company: "Your Company"

# Primary LLM - NVIDIA (used for ALL background processing)
llm:
  provider: "openai"
  api_key: "${{NVIDIA_API_KEY}}"
  base_url: "https://integrate.api.nvidia.com/v1"
  model: "nvidia/llama-3.3-nemotron-super-49b-v1"
  temperature: 0.7
  max_tokens: 8192
  context_window: 32768

# Video Analysis LLM - NVIDIA Cosmos
llm_video:
  provider: "openai"
  api_key: "${{NVIDIA_API_KEY}}"
  base_url: "https://integrate.api.nvidia.com/v1"
  model: "nvidia/cosmos-reason2-8b"
  temperature: 0.3
  max_tokens: 4096

# Fallback LLM - Claude (only for user-facing requests when NVIDIA fails)
llm_fallback:
  provider: "anthropic"
  api_key: "${{ANTHROPIC_API_KEY}}"
  model: "claude-sonnet-4-20250514"
  temperature: 0.7
  max_tokens: 8192

# Meeting processing
meeting:
  recording_dir: "{jarvis_home}/recordings"
  frame_interval_seconds: 30
  max_recording_minutes: 120
  audio_device: "BlackHole 2ch"

# Playbook automation
playbook:
  stale_deal_days: 7
  critical_stale_days: 14
  auto_research_on_new_account: true
  auto_meddpicc_on_meeting: true
  auto_followup_draft: true

# Orchestrator
orchestrator:
  health_check_interval: 30
  component_restart_threshold: 5
  cycle_interval: 60

# Notifications
notifications:
  telegram_enabled: false
  desktop_enabled: true

# Safety
safety:
  enabled: true
  max_actions_per_minute: 10

# OpenCode observer (optional)
opencode_db_path: "~/.local/share/opencode/conversations.db"
killswitch_path: "{jarvis_home}/data/.killswitch"
"""

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content)
    print(f"  Generated config: {config_path}")
    print(f"  JARVIS_HOME: {jarvis_home}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate JARVIS config")
    parser.add_argument("--jarvis-home", default=os.environ.get(
        "JARVIS_HOME", str(Path.home() / "Documents" / "claude space" / "JARVIS")
    ))
    args = parser.parse_args()
    generate_config(args.jarvis_home)
