#!/usr/bin/env python3
"""
Central config generator for JARVIS.
Generates all config files with correct local paths at setup time.
No hardcoded paths — everything resolved from runtime detection.
"""

import argparse
import json
import os
import sys
from pathlib import Path


def expand_user_path(p: str) -> str:
    """Expand ~ and resolve to absolute path."""
    return str(Path(p).expanduser().resolve())


def detect_opencode_db() -> str:
    """Detect OpenCode database path per OS."""
    home = Path.home()
    candidates = [
        home / ".local" / "share" / "opencode" / "opencode.db",
        home / "Library" / "Application Support" / "Accomplish" / "opencode" / "opencode.db",
    ]
    for p in candidates:
        if p.exists():
            return str(p)
    # Default to Linux convention (works on macOS too if OpenCode installed)
    return str(candidates[0])


def detect_opencode_tool_output() -> str:
    """Detect OpenCode tool output directory per OS."""
    home = Path.home()
    candidates = [
        home / ".local" / "share" / "opencode" / "tool-output",
        home / "Library" / "Application Support" / "Accomplish" / "opencode" / "tool-output",
    ]
    for p in candidates:
        if p.parent.exists():
            return str(p)
    return str(candidates[0])


def detect_opencode_log_dir() -> str:
    """Detect OpenCode log directory per OS."""
    home = Path.home()
    candidates = [
        home / ".local" / "share" / "opencode" / "log",
        home / "Library" / "Application Support" / "Accomplish" / "opencode" / "log",
    ]
    for p in candidates:
        if p.parent.exists():
            return str(p)
    return str(candidates[0])


def generate_jarvis_yaml(jarvis_home: str, repo_root: Path, claude_space: str = ""):
    """Generate jarvis/config/jarvis.yaml."""
    config_path = repo_root / "jarvis" / "config" / "jarvis.yaml"
    opencode_db = detect_opencode_db()

    cs_line = f'claude_space: "{claude_space}"' if claude_space else 'claude_space: ""'

    content = f"""# JARVIS v2 Configuration — Auto-generated by setup.sh
# Re-run setup.sh to regenerate, or edit manually.

# Paths (resolved for this machine)
workspace_root: "{jarvis_home}"
data_dir: "{jarvis_home}/data"
logs_dir: "{jarvis_home}/logs"
temp_dir: "{jarvis_home}/data/cache"

# Claude workspace — set by setup.sh or .env
{cs_line}

# Identity
identity:
  name: "YOUR_NAME"
  initials: "XY"
  title: "Account Executive + Solution Consultant"
  role: "Sales & Presales"
  company: "Your Company"

# NVIDIA LLM Models — each model used for its specific expertise
# All run concurrently via the async worker pool (3 parallel workers)
# All use the same NVIDIA API endpoint and key
llm_models:
  # General text reasoning — primary workhorse for most tasks
  text:
    model: "nvidia/llama-3.3-nemotron-super-49b-v1"
    temperature: 0.7
    max_tokens: 8192
    context_window: 32768

  # Long-context — Nemotron 3 Super 120B (1M token window)
  # Used for: full account dossiers, large RFPs, long transcripts, cross-deal analysis
  long_context:
    model: "nvidia/nemotron-3-super-120b"
    temperature: 0.3
    max_tokens: 32768
    context_window: 1048576

  # Video/slide analysis — NVIDIA Cosmos multimodal
  video:
    model: "nvidia/cosmos-reason2-8b"
    temperature: 0.3
    max_tokens: 4096
    context_window: 8192

  # Audio transcription — Whisper large v3
  audio:
    model: "nvidia/whisper-large-v3-turbo"
    temperature: 0.0
    max_tokens: 4096

  # Code/technical analysis
  code:
    model: "nvidia/qwen2.5-coder-32b-instruct"
    temperature: 0.2
    max_tokens: 8192
    context_window: 32768

  # Lightweight/quick tasks — classification, tagging, short summaries
  quick:
    model: "nvidia/mistral-nemo-minitron-8b-8k-instruct"
    temperature: 0.5
    max_tokens: 2048
    context_window: 8192

  # Deep reasoning — multi-step competitive analysis, demo strategy, battlecard
  # Step 3.5 Flash outperforms Nemotron Ultra for structured multi-step reasoning tasks
  reasoning:
    model: "step/step-3-5-flash"
    temperature: 0.4
    max_tokens: 8192
    context_window: 128000

llm_nvidia_base_url: "https://integrate.api.nvidia.com/v1"

# Fallback LLM - Claude (only for user-facing requests when NVIDIA fails)
llm_fallback:
  provider: "anthropic"
  api_key: "${{ANTHROPIC_API_KEY}}"
  model: "claude-sonnet-4-20250514"
  temperature: 0.7
  max_tokens: 8192

# Meeting processing
meeting:
  recording_dir: "{jarvis_home}/recordings"
  frame_interval_seconds: 30
  max_recording_minutes: 120

# Playbook automation
playbook:
  stale_deal_days: 7
  critical_stale_days: 14
  auto_research_on_new_account: true
  auto_meddpicc_on_meeting: true
  auto_followup_draft: true

# Orchestrator
orchestrator:
  health_check_interval: 30
  component_restart_threshold: 5
  cycle_interval: 60

# Notifications
notifications:
  telegram_enabled: false
  desktop_enabled: true

# Safety
safety:
  enabled: true
  max_actions_per_minute: 10

# OpenCode integration
opencode_db_path: "{opencode_db}"
killswitch_path: "{jarvis_home}/data/.killswitch"
"""

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(content)
    print(f"  jarvis.yaml → {config_path}")


def generate_mcp_observer_json(jarvis_home: str, repo_root: Path):
    """Generate config/mcp-observer.json with detected paths."""
    config_dir = repo_root / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "mcp-observer.json"

    config = {
        "opencode": {
            "dbPath": detect_opencode_db(),
            "logDir": detect_opencode_log_dir(),
            "toolOutputDir": detect_opencode_tool_output()
        },
        "observer": {
            "port": 3000,
            "wsPort": 3001,
            "pollInterval": 1000,
            "maxSessions": 100
        },
        "mcp": {
            "serverName": "opencode-observer",
            "transport": "stdio"
        },
        "logging": {
            "level": "info",
            "file": f"{jarvis_home}/logs/observer.log"
        }
    }

    config_path.write_text(json.dumps(config, indent=2) + "\n")
    print(f"  mcp-observer.json → {config_path}")


def generate_env_file(jarvis_home: str, repo_root: Path,
                      nvidia_key: str = "", anthropic_key: str = "",
                      claude_space: str = ""):
    """Generate .env file."""
    env_path = repo_root / ".env"

    content = f"""# JARVIS v2 — Auto-generated by setup.sh
# Edit API keys below, then run: ./start_jarvis.sh

# NVIDIA API Key (PRIMARY — used for all background LLM processing)
# Get from: https://build.nvidia.com/
NVIDIA_API_KEY={nvidia_key or 'YOUR_NVIDIA_API_KEY_HERE'}

# Anthropic API Key (FALLBACK — only used for user-facing requests)
ANTHROPIC_API_KEY={anthropic_key or ''}

# JARVIS home directory (your deal data)
JARVIS_HOME={jarvis_home}

# Claude workspace — the folder where you use Claude Desktop / Claude Code
CLAUDE_SPACE={claude_space or ''}

# Optional: Telegram bot for mobile notifications
TELEGRAM_BOT_TOKEN=
"""

    env_path.write_text(content)
    print(f"  .env → {env_path}")


def generate_observer_env(jarvis_home: str, repo_root: Path):
    """Generate mcp-opencode-observer/.env with detected paths."""
    env_path = repo_root / "mcp-opencode-observer" / ".env"

    content = f"""# OpenCode Observer — Auto-generated by setup.sh
OPENCODE_DB_PATH={detect_opencode_db()}
OPENCODE_LOG_DIR={detect_opencode_log_dir()}
OPENCODE_TOOL_OUTPUT_DIR={detect_opencode_tool_output()}
OPENCODE_OBSERVER_PORT=3000
OPENCODE_OBSERVER_WS_PORT=3001
OPENCODE_OBSERVER_POLL_INTERVAL=1000
"""

    env_path.write_text(content)
    print(f"  observer/.env → {env_path}")


def generate_all(jarvis_home: str, claude_space: str = "",
                 nvidia_key: str = "", anthropic_key: str = ""):
    """Generate all config files."""
    repo_root = Path(__file__).resolve().parent.parent
    jarvis_home = expand_user_path(jarvis_home)

    print(f"  JARVIS_HOME: {jarvis_home}")
    print(f"  CLAUDE_SPACE: {claude_space or '(disabled)'}")
    print(f"  OpenCode DB: {detect_opencode_db()}")

    # Create data directories
    dirs = [
        "ACCOUNTS", "MEETINGS", "MEMORY", "MEMORY/patterns",
        "data/personas", "data/templates", "data/meeting_queue",
        "data/cache", "data/history", "logs", "recordings",
        "ACCOUNTS/_template/MEETINGS", "ACCOUNTS/_template/DOCUMENTS",
        "ACCOUNTS/_template/EMAILS", "ACCOUNTS/_template/INTEL",
    ]
    for d in dirs:
        (Path(jarvis_home) / d).mkdir(parents=True, exist_ok=True)

    # Create JARVIS_BRAIN.md if missing
    brain_path = Path(jarvis_home) / "JARVIS_BRAIN.md"
    if not brain_path.exists():
        brain_path.write_text(
            "# JARVIS Brain — Conversation Intelligence Log\n\n"
            "*Claude Desktop appends entries here.*\n"
            "*JARVIS routes intelligence to ACCOUNTS/ automatically.*\n\n"
            "---\n"
        )

    print("\n  Generating configs:")
    generate_jarvis_yaml(jarvis_home, repo_root, claude_space)
    generate_mcp_observer_json(jarvis_home, repo_root)
    generate_env_file(jarvis_home, repo_root, nvidia_key, anthropic_key, claude_space)
    generate_observer_env(jarvis_home, repo_root)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate all JARVIS config files")
    parser.add_argument("--jarvis-home",
                        default=os.environ.get("JARVIS_HOME", str(Path.home() / "JARVIS")))
    parser.add_argument("--claude-space", default="")
    parser.add_argument("--nvidia-key", default="")
    parser.add_argument("--anthropic-key", default="")
    args = parser.parse_args()

    generate_all(
        jarvis_home=args.jarvis_home,
        claude_space=args.claude_space,
        nvidia_key=args.nvidia_key,
        anthropic_key=args.anthropic_key,
    )
    print("\n  Config generation complete.")
