#!/usr/bin/env python3
"""JARVIS Dashboard Server — reads all account data from JARVIS_HOME."""

import http.server
import socketserver
import json
import os
import sys
from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse, parse_qs

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
PORT = 8080
STATIC_DIR = Path(__file__).parent / "static"


def get_jarvis_home() -> Path:
    env = os.environ.get("JARVIS_HOME") or os.environ.get("JARVIS_DATA_DIR")
    if env:
        return Path(env).expanduser()
    repo_root = Path(__file__).parent.parent.parent
    env_file = repo_root / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if line.startswith("JARVIS_HOME="):
                val = line.split("=", 1)[1].strip().strip('"').strip("'")
                return Path(val).expanduser()
    return Path.home() / "JARVIS"


def read_json(path: Path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


def file_mtime(path: Path) -> str:
    try:
        ts = path.stat().st_mtime
        return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return ""


def is_placeholder(text: str) -> bool:
    """Return True if the file is still a template placeholder."""
    if not text or len(text.strip()) < 30:
        return True
    markers = ["*Generating...*", "*Waiting for", "*Auto-generated by JARVIS*\n\n---\n**Created:**",
               "JARVIS is generating", "Waiting for discovery", "Not generated yet"]
    for m in markers:
        if m in text:
            return True
    return False


def get_intel_files(account_dir: Path) -> list:
    intel_dir = account_dir / "INTEL"
    if not intel_dir.exists():
        return []
    files = []
    for f in sorted(intel_dir.iterdir()):
        if f.is_file() and f.suffix in (".md", ".txt", ".json"):
            content = read_text(f)
            files.append({
                "name": f.name,
                "size": len(content),
                "modified": file_mtime(f),
                "preview": content[:400].strip(),
                "content": content,
                "is_json": f.suffix == ".json",
            })
    return files


def build_account_summary(account_dir: Path) -> dict:
    name = account_dir.name
    meddpicc = read_json(account_dir / "meddpicc.json") or {}
    score = meddpicc.get("score", 0)
    max_score = meddpicc.get("max_score", 8)
    stage_data = read_json(account_dir / "deal_stage.json") or {}
    stage = stage_data.get("stage", "new_account")

    last_activity = None
    activities_file = account_dir / "activities.jsonl"
    if activities_file.exists():
        lines = activities_file.read_text().strip().splitlines()
        if lines:
            try:
                last = json.loads(lines[-1])
                last_activity = last.get("date") or last.get("timestamp", "")[:10]
            except Exception:
                pass

    contacts_data = read_json(account_dir / "contacts.json") or {}
    bc_data = read_json(account_dir / "BATTLECARD" / "battlecard_data.json") or {}
    prop_data = read_json(account_dir / "PROPOSAL" / "proposal_data.json") or {}

    # Discovery quality check — has actual notes, not just template
    disc_notes = read_text(account_dir / "DISCOVERY" / "final_discovery.md")
    has_discovery = not is_placeholder(disc_notes) and len(disc_notes) > 150

    days_stale = None
    if last_activity:
        try:
            delta = datetime.now() - datetime.strptime(last_activity[:10], "%Y-%m-%d")
            days_stale = delta.days
        except Exception:
            pass

    # INTEL intel check
    intel_dir = account_dir / "INTEL"
    intel_count = len(list(intel_dir.glob("*.md"))) if intel_dir.exists() else 0

    # Section freshness timestamps
    section_times = {}
    sections = {
        "battlecard": account_dir / "BATTLECARD" / "battlecard.md",
        "discovery":  account_dir / "DISCOVERY" / "final_discovery.md",
        "demo":       account_dir / "DEMO_STRATEGY" / "demo_strategy.md",
        "risk":       account_dir / "RISK_REPORT" / "risk_report.md",
        "value":      account_dir / "VALUE_ARCHITECTURE" / "roi_model.md",
        "proposal":   account_dir / "PROPOSAL" / "proposal_data.json",
        "sow":        account_dir / "SOW" / "sow.md",
    }
    for k, p in sections.items():
        section_times[k] = file_mtime(p)

    return {
        "name": name,
        "stage": stage,
        "stage_updated": stage_data.get("last_updated", ""),
        "meddpicc_score": score,
        "meddpicc_max": max_score,
        "meddpicc_pct": round((score / max_score) * 100) if max_score else 0,
        "meddpicc_dimensions": {
            "metrics":           meddpicc.get("metrics", 0),
            "economic_buyer":    meddpicc.get("economic_buyer", 0),
            "decision_criteria": meddpicc.get("decision_criteria", 0),
            "decision_process":  meddpicc.get("decision_process", 0),
            "paper_process":     meddpicc.get("paper_process", 0),
            "implicate_pain":    meddpicc.get("implicate_pain", 0),
            "champion":          meddpicc.get("champion", 0),
            "competition":       meddpicc.get("competition", 0),
        },
        "win_probability": bc_data.get("win_probability"),
        "last_activity": last_activity,
        "days_stale": days_stale,
        "contacts_count": len(contacts_data.get("contacts", [])),
        "has_discovery": has_discovery,
        "proposal_status": prop_data.get("status", ""),
        "competitors": bc_data.get("competitors", []),
        "intel_count": intel_count,
        "section_times": section_times,
        "notes": read_json(account_dir / "notes.json") or {},
        "arr": stage_data.get("arr") or prop_data.get("arr"),
    }


def build_account_detail(account_dir: Path) -> dict:
    summary = build_account_summary(account_dir)

    def section(path, key=None):
        txt = read_text(path)
        return {"content": txt, "modified": file_mtime(path), "placeholder": is_placeholder(txt)}

    # Activities — full content
    activities = []
    act_file = account_dir / "activities.jsonl"
    if act_file.exists():
        for line in reversed(act_file.read_text().strip().splitlines()[-30:]):
            try:
                activities.append(json.loads(line))
            except Exception:
                pass

    # Conversations from INTEL
    conv_log = read_text(account_dir / "INTEL" / "conversation_log.md")
    conv_jsonl = account_dir / "INTEL" / "conversations.jsonl"
    conversations = []
    if conv_jsonl.exists():
        for line in conv_jsonl.read_text().strip().splitlines()[-20:]:
            try:
                conversations.append(json.loads(line))
            except Exception:
                pass

    return {
        **summary,
        "discovery": {
            "prep":  section(account_dir / "DISCOVERY" / "discovery_prep.md"),
            "notes": section(account_dir / "DISCOVERY" / "final_discovery.md"),
        },
        "battlecard": {
            "markdown": section(account_dir / "BATTLECARD" / "battlecard.md"),
            "data":     read_json(account_dir / "BATTLECARD" / "battlecard_data.json") or {},
        },
        "demo": {
            "strategy": section(account_dir / "DEMO_STRATEGY" / "demo_strategy.md"),
            "script":   section(account_dir / "DEMO_STRATEGY" / "demo_script.md"),
        },
        "risk":  {"report": section(account_dir / "RISK_REPORT" / "risk_report.md")},
        "value": {
            "roi":  section(account_dir / "VALUE_ARCHITECTURE" / "roi_model.md"),
            "tco":  section(account_dir / "VALUE_ARCHITECTURE" / "tco_analysis.md"),
            "data": read_json(account_dir / "VALUE_ARCHITECTURE" / "value_data.json") or {},
        },
        "proposal": {
            "data":       read_json(account_dir / "PROPOSAL" / "proposal_data.json") or {},
            "html_exists": (account_dir / "PROPOSAL" / "proposal.html").exists(),
            "modified":   file_mtime(account_dir / "PROPOSAL" / "proposal_data.json"),
        },
        "sow": section(account_dir / "SOW" / "sow.md"),
        "architecture": {
            "diagram":    section(account_dir / "ARCHITECTURE" / "architecture_diagram.md"),
            "html_exists": (account_dir / "ARCHITECTURE" / "architecture_diagram.html").exists(),
        },
        "next_steps": section(account_dir / "NEXT_STEPS" / "next_steps.md"),
        "contacts":   (read_json(account_dir / "contacts.json") or {}).get("contacts", []),
        "actions":    {"content": read_text(account_dir / "actions.md"), "modified": file_mtime(account_dir / "actions.md")},
        "summary_md": read_text(account_dir / "summary.md"),
        "activities": activities,
        "intel_files": get_intel_files(account_dir),
        "conversation_log": conv_log,
        "conversations": conversations,
        "rfi": {
            "analysis":  section(account_dir / "RFI" / "rfi_analysis.md"),
            "responses": section(account_dir / "RFI" / "rfi_responses.md"),
        },
    }


def get_accounts(jarvis_home: Path) -> list:
    accounts_dir = jarvis_home / "ACCOUNTS"
    if not accounts_dir.exists():
        return []
    result = []
    for entry in sorted(accounts_dir.iterdir()):
        if entry.is_dir() and not entry.name.startswith((".", "_")):
            try:
                result.append(build_account_summary(entry))
            except Exception:
                pass
    return result


def get_pipeline(accounts: list) -> dict:
    stages = {}
    for acc in accounts:
        s = acc.get("stage", "new_account")
        stages.setdefault(s, []).append(acc)
    return stages


def get_activity_feed(jarvis_home: Path, limit: int = 60) -> list:
    accounts_dir = jarvis_home / "ACCOUNTS"
    events = []
    if not accounts_dir.exists():
        return events
    for entry in accounts_dir.iterdir():
        if not entry.is_dir() or entry.name.startswith((".", "_")):
            continue
        act_file = entry / "activities.jsonl"
        if act_file.exists():
            for line in act_file.read_text().strip().splitlines():
                try:
                    ev = json.loads(line)
                    ev["account"] = entry.name
                    events.append(ev)
                except Exception:
                    pass
        # Also pull from INTEL/conversation_log.md snippets
        conv = entry / "INTEL" / "conversations.jsonl"
        if conv.exists():
            for line in conv.read_text().strip().splitlines()[-5:]:
                try:
                    ev = json.loads(line)
                    ev["account"] = entry.name
                    ev["source"] = ev.get("source", "conversation")
                    events.append(ev)
                except Exception:
                    pass
    events.sort(key=lambda x: str(x.get("timestamp") or x.get("date", "")), reverse=True)
    return events[:limit]


def get_logs(jarvis_home: Path, lines: int = 100) -> list:
    log_file = jarvis_home / "logs" / "orchestrator.log"
    if not log_file.exists():
        return []
    return log_file.read_text(errors="replace").splitlines()[-lines:]


def get_stats(accounts: list, jarvis_home: Path) -> dict:
    total = len(accounts)
    by_stage = {}
    stale = 0
    medd_sum = 0
    for acc in accounts:
        s = acc.get("stage", "new_account")
        by_stage[s] = by_stage.get(s, 0) + 1
        if acc.get("days_stale") and acc["days_stale"] > 7:
            stale += 1
        medd_sum += acc.get("meddpicc_pct", 0)
    avg_medd = round(medd_sum / total) if total else 0
    log_lines = 0
    log_file = jarvis_home / "logs" / "orchestrator.log"
    if log_file.exists():
        log_lines = log_file.read_text(errors="replace").count("\n")
    return {
        "total_accounts": total,
        "by_stage": by_stage,
        "stale_deals": stale,
        "avg_meddpicc_pct": avg_medd,
        "log_events": log_lines,
        "active_stage_counts": {
            "discovery": by_stage.get("discovery", 0),
            "demo": by_stage.get("demo", 0),
            "proposal": by_stage.get("proposal", 0),
            "negotiation": by_stage.get("negotiation", 0),
        }
    }


class DashboardHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        self.jarvis_home = get_jarvis_home()
        super().__init__(*args, directory=str(STATIC_DIR), **kwargs)

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        params = parse_qs(parsed.query)
        if path in ("/", "/index.html"):
            self.serve_static("index.html")
        elif path.endswith((".css", ".js")):
            self.serve_static(path.lstrip("/"))
        elif path.startswith("/api/"):
            self.handle_api(path, params)
        else:
            self.send_error(404)

    def serve_static(self, filename):
        try:
            content = (STATIC_DIR / filename).read_bytes()
            self.send_response(200)
            ct = {"html": "text/html; charset=utf-8", "css": "text/css", "js": "application/javascript"}
            self.send_header("Content-Type", ct.get(filename.rsplit(".", 1)[-1], "text/plain"))
            self.end_headers()
            self.wfile.write(content)
        except FileNotFoundError:
            self.send_error(404)

    def json_response(self, data):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(data, default=str).encode())

    def handle_api(self, path, params):
        try:
            if path == "/api/status":
                pid_ok = False
                try:
                    pid = int((Path.cwd() / ".jarvis.pid").read_text().strip())
                    os.kill(pid, 0); pid_ok = True
                except Exception:
                    pass
                accounts = get_accounts(self.jarvis_home)
                self.json_response({
                    "running": pid_ok,
                    "jarvis_home": str(self.jarvis_home),
                    "timestamp": datetime.now().isoformat(),
                    "accounts_count": len(accounts),
                })
            elif path == "/api/accounts":
                self.json_response(get_accounts(self.jarvis_home))
            elif path.startswith("/api/accounts/"):
                parts = path.split("/api/accounts/", 1)[1].rstrip("/").split("/")
                name = parts[0]
                account_dir = self.jarvis_home / "ACCOUNTS" / name
                if not account_dir.exists():
                    self.json_response({"error": f"Account '{name}' not found"})
                    return
                if len(parts) == 1:
                    self.json_response(build_account_detail(account_dir))
                elif parts[1] == "intel":
                    self.json_response(get_intel_files(account_dir))
                else:
                    self.json_response({"error": "Unknown sub-path"})
            elif path == "/api/pipeline":
                self.json_response(get_pipeline(get_accounts(self.jarvis_home)))
            elif path == "/api/activity":
                limit = int(params.get("limit", [60])[0])
                self.json_response(get_activity_feed(self.jarvis_home, limit))
            elif path == "/api/stats":
                accounts = get_accounts(self.jarvis_home)
                self.json_response(get_stats(accounts, self.jarvis_home))
            elif path == "/api/logs":
                lines = int(params.get("lines", [100])[0])
                self.json_response({"lines": get_logs(self.jarvis_home, lines)})
            else:
                self.json_response({"error": "Unknown endpoint"})
        except Exception as e:
            self.json_response({"error": str(e)})

    def log_message(self, fmt, *args):
        pass


def run():
    os.chdir(Path(__file__).parent.parent.parent)
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("", PORT), DashboardHandler) as httpd:
        print(f"JARVIS Dashboard → http://localhost:{PORT}")
        httpd.serve_forever()


if __name__ == "__main__":
    run()
